version: 2.1

commands:
  destroy_environment:
    # parameters:
    #   when_to_run:
    #     type: string
    #     default: on_fail
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name templateUdacity
          when:  on_fail

jobs:
  roll_back_test:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Infra Stack Creation
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name templateUdacity
      - run: return 1
      - destroy_environment
          

workflows:
  rollback_workflow:
    jobs:
      - roll_back_test